name = "stovokor-website"
main = "src/worker.js"
compatibility_date = "2026-09-10"

[assets]
directory = "."
binding = "ASSETS"
html_handling = "none"
not_found_handling = "none"

[vars]
TO_EMAIL = "info@stovokor.ai"
FROM_EMAIL = "website@stovokor.ai"

[[send_email]]
name = "EMAIL"
